version: '3.8'

services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_USERNAME=admin
      - EUREKA_PASSWORD=secure_password_123
    networks:
      - car-rental-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - eureka-logs:/var/log/eureka-server

  # Redis for API Gateway rate limiting
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - car-rental-network
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

networks:
  car-rental-network:
    driver: bridge
    name: car-rental-network

volumes:
  eureka-logs:
    driver: local
  redis-data:
    driver: local